name: CI
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run env
        run: env

      - name: Create branch and commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          echo 1 > 1.txt
          git checkout -b add
          git add 1.txt
          git commit -m "feat: add 1.txt"
          git push -u origin add

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source-branch: add
          base-branch: main
          title: "feat: add 1.txt"
          body: "自动创建文件"
          labels: enhancement
