name: releases

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  

permissions:
  contents: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: containers/skopeo
          ref: v1.24.0
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run Go Multi-Platform Build Action
        id: build
        uses: chihqiang/gobuild-action@develop
        with:
          main_go: ./cmd/skopeo
          archs: "linux/amd64 linux/arm64 linux/ppc64le darwin/amd64 darwin/arm64 windows/386 windows/amd64"
          bin_name: skopeo
          build_flags: "-mod=vendor '-buildmode=pie' -ldflags '-extldflags -static' -gcflags '' -tags 'exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp'"
          add_files: |
            README.md
            LICENSE
      - name: upload-gh-release-assets
        uses: chihqiang/upload-asset-action@v0.2.0
  
